// ingredients
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR';

// burger
export const GET_MAIN_BURGER = 'GET_MAIN_BURGER';
export const ADD_INGREDIENT_IN_BURGER = 'ADD_INGREDIENT_IN_BURGER';
export const REMOVE_INGREDIENT_IN_BURGER = 'REMOVE_INGREDIENT_IN_BURGER';
