// ingredients
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR';

// burger
export const SET_BURGER = 'SET_BURGER';
export const ADD_INGREDIENT_IN_BURGER = 'ADD_INGREDIENT_IN_BURGER';
export const MOVE_INGREDIENT_IN_BURGER = 'MOVE_INGREDIENT_IN_BURGER';
export const REMOVE_INGREDIENT_IN_BURGER = 'REMOVE_INGREDIENT_IN_BURGER';

// current ingredient
export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT';
export const REMOVE_CURRENT_INGREDIENT = 'REMOVE_CURRENT_INGREDIENT';

// order
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER';
export const REMOVE_CURRENT_ORDER = 'REMOVE_CURRENT_ORDER';
